# Generated by Django 4.2.13 on 2024-07-14 20:14

import base.base_upload_handlers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.base_upload_handlers.handle_menu_file)),
                ('is_non_veg', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(limit_choices_to={'user_type': 'rt'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('P', 'In Progress')], default='P', max_length=10)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'C'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'R'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_driver', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='order_service.menuitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
